- name: Configure Cisco NX-OS Devices
  hosts: routers
  gather_facts: no
  tasks:
    - name: Set hostname on NX-OS
      cisco.nxos.nxos_config:
        lines:
          - hostname {{ inventory_hostname }}
    - name: Configure interface IP
      cisco.nxos.nxos_config:
        lines:
          - interface Ethernet1/1
          - ip address 192.168.10.1 255.255.255.0

